EPSILON = 0.00001
ACCELERATION_LIM = 0.0002
ACCELERATION_NUMVALS = 3
HOP_DISTANCE_THRESHOLD = 0.001
XY_LIM = 1.0
XY_AXISVALS = 3
XYDOT_LIM = 0.002
XYDOT_AXISVALS = 3
XYDOT_HOP_THRESH = 0.0008
ACC_NOISE_STD = 0.00001
MAX_DRONE_SPEED = 0.00285
MAX_CAR_SPEED = 0.007
VALID_FLIGHT_EDGE_DIST_RATIO = 1.1
MC_GENERATIVE_NUMSAMPLES = 2